# tmh Fish integration. Generated by `tmh shell init fish`.

function tmh
    switch "$argv[1]"
        case generate
            command tmh generate --shell fish $argv[2..-1]
        case agent
            command tmh agent --shell fish $argv[2..-1]
        case config shell help version -h --help --version
            command tmh $argv
        case '*'
            command tmh --shell fish $argv
    end
end

function __tmh_fish_query --argument-names mode value
    set value (string trim -- "$value" | string collect)
    if test "$mode" = generate
        string match -q 'tmh agent *' -- "$value"; and return 2
        if string match -q 'tmh generate *' -- "$value"
            set value (string replace 'tmh generate ' '' -- "$value" | string collect)
        else if string match -q 'tmh *' -- "$value"
            set value (string replace 'tmh ' '' -- "$value" | string collect)
        end
    else
        string match -q 'tmh generate *' -- "$value"; and return 2
        if string match -q 'tmh agent *' -- "$value"
            set value (string replace 'tmh agent ' '' -- "$value" | string collect)
        end
    end
    test -n "$value"; or return 1
    set -g __tmh_widget_query "$value"
end

function __tmh_generate_widget
    set -l original (commandline | string collect -N)
    set -l original_cursor (commandline -C)
    set -e __tmh_widget_query
    __tmh_fish_query generate "$original"; or return $status
    set -l query "$__tmh_widget_query"
    set -e __tmh_widget_query
    set -l generated (command tmh --shell fish -- "$query")
    set -l command_status $status
    if test $command_status -ne 0 -o -z "$generated"
        commandline -r -- "$original"
        commandline -C $original_cursor
        commandline -f repaint
        test $command_status -ne 0; and return $command_status
        return 1
    end
    commandline -r -- "$generated"
    commandline -C (string length -- "$generated")
    commandline -f repaint
end

function __tmh_agent_widget
    set -l original (commandline | string collect -N)
    set -l original_cursor (commandline -C)
    set -e __tmh_widget_query
    __tmh_fish_query agent "$original"; or return $status
    set -l query "$__tmh_widget_query"
    set -e __tmh_widget_query
    set -l generated (command tmh agent --shell fish -- "$query")
    set -l command_status $status
    if test $command_status -ne 0 -o -z "$generated"
        commandline -r -- "$original"
        commandline -C $original_cursor
        commandline -f repaint
        test $command_status -ne 0; and return $command_status
        return 1
    end
    commandline -r -- "$generated"
    commandline -C (string length -- "$generated")
    commandline -f repaint
end

if status is-interactive
    set -g __tmh_bind_mode '__TMH_BIND_MODE__'
    function __tmh_fish_bind --argument-names map key callback
        test "$__tmh_bind_mode" = none; and return
        if test "$__tmh_bind_mode" != force
            bind -M "$map" "$key" >/dev/null 2>&1; and return
        end
        bind -M "$map" "$key" "$callback"
    end
    for __tmh_map in default insert
        __tmh_fish_bind "$__tmh_map" \cx\cg __tmh_generate_widget
        __tmh_fish_bind "$__tmh_map" \cx\ca __tmh_agent_widget
    end
    set -e __tmh_map
    functions -e __tmh_fish_bind
    set -e __tmh_bind_mode
end
