# tmh Zsh integration. Generated by `tmh shell init zsh`.

_tmh_delegate_subcommand() {
  case "${1:-}" in
    config|shell|help|version|-h|--help|--version)
      return 0
      ;;
  esac
  return 1
}

_tmh_zsh_call() {
  case "${1:-}" in
    generate)
      shift
      command tmh generate --shell zsh "$@"
      ;;
    agent)
      shift
      command tmh agent --shell zsh "$@"
      ;;
    *)
      command tmh --shell zsh "$@"
      ;;
  esac
}

tmh() {
  if _tmh_delegate_subcommand "$@"; then
    command tmh "$@"
    return $?
  fi

  local generated rc
  generated="$(_tmh_zsh_call "$@")"
  rc=$?
  (( rc == 0 )) || return "$rc"
  [[ -n "$generated" ]] || return 1
  print -z -- "$generated"
}

_tmh_zsh_query() {
  local mode="$1" value="$2"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  if [[ "$mode" == generate ]]; then
    [[ "$value" == 'tmh agent '* ]] && return 2
    [[ "$value" == 'tmh generate '* ]] && value="${value#tmh generate }"
    [[ "$value" == 'tmh '* ]] && value="${value#tmh }"
  else
    [[ "$value" == 'tmh generate '* ]] && return 2
    [[ "$value" == 'tmh agent '* ]] && value="${value#tmh agent }"
  fi
  [[ -n "$value" ]] || return 1
  REPLY="$value"
}

_tmh_generate_widget() {
  local original="$BUFFER" original_cursor="$CURSOR" generated rc REPLY
  _tmh_zsh_query generate "$BUFFER" || {
    zle -M 'tmh: enter a generate request'
    return 1
  }
  generated="$(command tmh --shell zsh -- "$REPLY")"
  rc=$?
  if (( rc != 0 )) || [[ -z "$generated" ]]; then
    BUFFER="$original"
    CURSOR="$original_cursor"
    zle redisplay
    (( rc != 0 )) && return "$rc"
    return 1
  fi
  BUFFER="$generated"
  CURSOR=${#BUFFER}
  zle redisplay
}

_tmh_agent_widget() {
  local original="$BUFFER" original_cursor="$CURSOR" generated rc REPLY
  _tmh_zsh_query agent "$BUFFER" || {
    zle -M 'tmh: enter an agent request'
    return 1
  }
  generated="$(command tmh agent --shell zsh -- "$REPLY")"
  rc=$?
  if (( rc != 0 )) || [[ -z "$generated" ]]; then
    BUFFER="$original"
    CURSOR="$original_cursor"
    zle redisplay
    (( rc != 0 )) && return "$rc"
    return 1
  fi
  BUFFER="$generated"
  CURSOR=${#BUFFER}
  zle redisplay
}

if [[ -o interactive ]] && zmodload -F zsh/zle b:zle 2>/dev/null; then
  zle -N tmh-generate-widget _tmh_generate_widget
  zle -N tmh-agent-widget _tmh_agent_widget

  _tmh_bind_mode='__TMH_BIND_MODE__'
  _tmh_zsh_bind() {
    local map="$1" key="$2" widget="$3" current
    [[ "$_tmh_bind_mode" == none ]] && return 0
    if [[ "$_tmh_bind_mode" != force ]]; then
      current="$(bindkey -M "$map" "$key" 2>/dev/null || true)"
      [[ -n "$current" && "$current" != *undefined-key* ]] && return 0
    fi
    bindkey -M "$map" "$key" "$widget"
  }
  for _tmh_map in emacs viins; do
    _tmh_zsh_bind "$_tmh_map" '^X^G' tmh-generate-widget
    _tmh_zsh_bind "$_tmh_map" '^X^A' tmh-agent-widget
  done
  unset _tmh_map
  unfunction _tmh_zsh_bind
  unset _tmh_bind_mode
fi
