# tmh Bash integration. Generated by `tmh shell init bash`.

tmh() {
  case "${1:-}" in
    generate)
      shift
      command tmh generate --shell bash "$@"
      ;;
    agent)
      shift
      command tmh agent --shell bash "$@"
      ;;
    config|shell|help|version|-h|--help|--version)
      command tmh "$@"
      ;;
    *)
      command tmh --shell bash "$@"
      ;;
  esac
}

_tmh_bash_query() {
  local mode="$1" value="$2"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  if [[ "$mode" == generate ]]; then
    [[ "$value" == 'tmh agent '* ]] && return 2
    [[ "$value" == 'tmh generate '* ]] && value="${value#tmh generate }"
    [[ "$value" == 'tmh '* ]] && value="${value#tmh }"
  else
    [[ "$value" == 'tmh generate '* ]] && return 2
    [[ "$value" == 'tmh agent '* ]] && value="${value#tmh agent }"
  fi
  [[ -n "$value" ]] || return 1
  TMH_WIDGET_QUERY="$value"
}

_tmh_generate_widget() {
  local original="$READLINE_LINE" original_point="$READLINE_POINT" generated rc TMH_WIDGET_QUERY
  _tmh_bash_query generate "$READLINE_LINE" || return 1
  generated="$(command tmh --shell bash -- "$TMH_WIDGET_QUERY")"
  rc=$?
  if (( rc != 0 )) || [[ -z "$generated" ]]; then
    READLINE_LINE="$original"
    READLINE_POINT="$original_point"
    (( rc != 0 )) && return "$rc"
    return 1
  fi
  READLINE_LINE="$generated"
  local LC_ALL=C
  READLINE_POINT=${#READLINE_LINE}
}

_tmh_agent_widget() {
  local original="$READLINE_LINE" original_point="$READLINE_POINT" generated rc TMH_WIDGET_QUERY
  _tmh_bash_query agent "$READLINE_LINE" || return 1
  generated="$(command tmh agent --shell bash -- "$TMH_WIDGET_QUERY")"
  rc=$?
  if (( rc != 0 )) || [[ -z "$generated" ]]; then
    READLINE_LINE="$original"
    READLINE_POINT="$original_point"
    (( rc != 0 )) && return "$rc"
    return 1
  fi
  READLINE_LINE="$generated"
  local LC_ALL=C
  READLINE_POINT=${#READLINE_LINE}
}

if [[ $- == *i* ]]; then
  _tmh_bind_mode='__TMH_BIND_MODE__'
  if (( BASH_VERSINFO[0] >= 4 )); then
    _tmh_bash_key_bound() {
      local map="$1" key="$2"
      bind -m "$map" -P 2>/dev/null | grep -Fq "$key" && return 0
      bind -m "$map" -S 2>/dev/null | grep -Fq "$key" && return 0
      if bind -m "$map" -X >/dev/null 2>&1; then
        bind -m "$map" -X 2>/dev/null | grep -Fq "$key"
        return $?
      fi
      # Older Bash 4 releases cannot enumerate bind -x callbacks. Treat the
      # key as occupied unless the user explicitly selected --force-bind.
      return 0
    }
    _tmh_bash_bind() {
      local map="$1" key="$2" callback="$3"
      [[ "$_tmh_bind_mode" == none ]] && return 0
      if [[ "$_tmh_bind_mode" != force ]] && _tmh_bash_key_bound "$map" "$key"; then
        return 0
      fi
      bind -m "$map" -x "$key:$callback"
    }
    for _tmh_map in emacs-standard vi-insert; do
      _tmh_bash_bind "$_tmh_map" '"\C-x\C-g"' _tmh_generate_widget
      _tmh_bash_bind "$_tmh_map" '"\C-x\C-a"' _tmh_agent_widget
    done
    unset _tmh_map
    unset -f _tmh_bash_bind _tmh_bash_key_bound
  elif [[ "$_tmh_bind_mode" != none && -z "${_TMH_BASH32_NOTICE_SHOWN:-}" ]]; then
    _TMH_BASH32_NOTICE_SHOWN=1
    printf '%s\n' 'tmh: Bash 3.2 supports command generation but not readline buffer widgets; use stdout or upgrade Bash.' >&2
  fi
  unset _tmh_bind_mode
fi
